repos:
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
  - id: black-jupyter

- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
  - id: nbdev_clean
    args:
      - --fname
      - .